CREATE DATABASE IF NOT EXISTS coreprotect;
CREATE DATABASE IF NOT EXISTS lwc;
CREATE DATABASE IF NOT EXISTS dev;

GRANT ALL PRIVILEGES ON coreprotect.* TO 'minecraft_user'@'%';
GRANT ALL PRIVILEGES ON lwc.* TO 'minecraft_user'@'%';
GRANT ALL PRIVILEGES ON dev.* TO 'minecraft_user'@'%';
FLUSH PRIVILEGES;
